### PR TITLE
Fixed phpstan issues

### PR DESCRIPTION
**Pull request by mabar**
PHPStan should not report any issues, so I removed it from allow_failure to prevent any new issues in future

### CODE REVIEW

**Comment by dg** [comment]
👎 for removing from allow_failure because it is big complication for me.

**Comment by mabar** [comment]
As you wish, reverted

**Comment by dg** [comment]
Why is annotation $components confusing?

**Comment by mabar** [comment]
There is also $components property with typehint `IComponent[]`

**Comment by dg** [comment]
Where?

**Comment by mabar** [comment]
https://github.com/nette/component-model/blob/master/src/ComponentModel/Container.php#L18-L25

**Comment by dg** [comment]
But it is a different private property.

**Comment by mabar** [comment]
How is anyone supposed to understand that two properties with same name are not the same one? It's not possible to do without magic.

**Comment by dg** [comment]
The second one is shortcut for getComponents(), presented for back compatibility. And magic is well documented https://doc.nette.org/cs/3.0/smartobject

**Pull request closed without merging**
