### PR TITLE
Resolve incompatibility with Nette\Forms 3.0

### PR DESCRIPTION
**Pull request by SendiMyrkr**
- bug fix? yes
- new feature? no
- BC break? not for 3.0

### CODE REVIEW

**Comment by dg** [comment]
Which bug it fixes?

**Comment by SendiMyrkr** [comment]
None filled, i found it when i installed nette 3.0.* on PHP 7.2

**Comment by matej21** [comment]
what error does it show? 
I don't see why there should be any incompatibility with nette forms 3.0 - there is no `?string` typehint in addComponent method in nette/forms

**Comment by SendiMyrkr** [comment]
Hm, i guess it's only aplha1 problem. Master looks ok.

**Comment by SendiMyrkr** [comment]
Sorry, not valid any more, i just used old alpha

**Pull request closed without merging**
